[theme]
primaryColor = "#ff2b2b"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
maxUploadSize = 40
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false